"""Initial tables

Revision ID: 0208c0995415
Revises: 
Create Date: 2026-09-06 18:38:06.218234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0208c0995415'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('angle', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_title'), 'topics', ['title'], unique=False)
    op.create_table('content_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hook', sa.String(), nullable=False),
    sa.Column('linkedin_post', sa.String(), nullable=False),
    sa.Column('instagram_caption', sa.String(), nullable=False),
    sa.Column('cta', sa.String(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_drafts_state'), 'content_drafts', ['state'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_url'), 'research_sources', ['url'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_posts_external_id'), 'published_posts', ['external_id'], unique=False)
    op.create_table('quality_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('aspect_ratio', sa.String(), nullable=False),
    sa.Column('composition', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('supporting_text', sa.String(), nullable=False),
    sa.Column('visual_subject', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('lighting', sa.String(), nullable=False),
    sa.Column('color_palette', sa.String(), nullable=False),
    sa.Column('typography', sa.String(), nullable=False),
    sa.Column('negative_prompt', sa.String(), nullable=False),
    sa.Column('brand_requirements', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['content_drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id')
    )
    op.create_table('analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['published_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    op.drop_table('visual_concepts')
    op.drop_table('quality_checks')
    op.drop_index(op.f('ix_published_posts_external_id'), table_name='published_posts')
    op.drop_table('published_posts')
    op.drop_table('generated_assets')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_research_sources_url'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_content_drafts_state'), table_name='content_drafts')
    op.drop_table('content_drafts')
    op.drop_index(op.f('ix_topics_title'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
