"""Add workflow models

Revision ID: c1b0baabe152
Revises: 0208c0995415
Create Date: 2026-09-06 19:30:37.643323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b0baabe152'
down_revision: Union[str, Sequence[str], None] = '0208c0995415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_strategy_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('strongest_topics', sa.JSON(), nullable=False),
    sa.Column('weakest_topics', sa.JSON(), nullable=False),
    sa.Column('strongest_formats', sa.JSON(), nullable=False),
    sa.Column('best_hooks', sa.JSON(), nullable=False),
    sa.Column('best_posting_times', sa.JSON(), nullable=False),
    sa.Column('engagement_trends', sa.JSON(), nullable=False),
    sa.Column('repeated_themes', sa.JSON(), nullable=False),
    sa.Column('content_fatigue', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logs', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_run_date'), 'pipeline_runs', ['run_date'], unique=True)
    op.add_column('analytics', sa.Column('impressions', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('reach', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('saves', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('profile_visits', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('followers_gained', sa.Integer(), nullable=False))
    op.drop_column('analytics', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('views', sa.INTEGER(), nullable=False))
    op.drop_column('analytics', 'followers_gained')
    op.drop_column('analytics', 'profile_visits')
    op.drop_column('analytics', 'saves')
    op.drop_column('analytics', 'reach')
    op.drop_column('analytics', 'impressions')
    op.drop_index(op.f('ix_pipeline_runs_run_date'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('content_strategy_profiles')
    # ### end Alembic commands ###
